Analysis of the data of lateral flow assay

--------------------------------------------------------------------------



Date: `r Sys.time()`

-----------------------------------------



Initial Data:

-----------------------------------------

````{r, echo=FALSE}

x <- file()

knitr::kable(x, format = "markdown")

````


Combined replicates:

-----------------------------------------

````{r, echo=FALSE}

x <- crep()

knitr::kable(x, format = "markdown")

````

Normalized Intensity Plot (Standardized Intensity vs Concentration):
-------------------------------------------------------------------------

````{r, echo=FALSE}

x.crep <- crep()

      nidata <- x.crep[,"NI.crep"]

      Concn.new <- x.crep[,"Concn"]
      sd.ni <- x.crep[,"NI.sdns"]

      ni.new <- as.data.frame(cbind(Concn.new,nidata,sd.ni))
      names(ni.new) <- c("x","y","sd")
      plot1 <- ggplot(data =ni.new, aes(x,y))+ ggtitle("Intensity vs Concentration")+
        geom_point(colour = "black", na.rm = TRUE)+
        geom_smooth(method = "lm", formula = y~x, se = FALSE, colour = "black")+
        geom_errorbar(aes(ymin= y-sd, ymax=y+sd), width=.2,
                      position=position_dodge(0.05))+
        xlab("Concentration (nM)") +
        ylab("Normalized Intensity (cl/tl) [arbitrary unit]")+
        stat_poly_eq(formula = y~x, aes(label = paste(..eq.label.., ..rr.label..,
                                                      sep = "~~~")),
                     parse = TRUE)

      plot1

````

Standardized Intensity Plot (Normalized Intensity vs Concentration):
-------------------------------------------------------------------------

````{r, echo=FALSE}

x.crep <- crep()
      sidata <- x.crep[,"SI.crep"]
      Concn.new <- x.crep[,"Concn"]
      sd.ni <- x.crep[,"SI.sdns"]
      si.new <- as.data.frame(cbind(Concn.new,sidata,sd.ni))
      names(si.new) <- c("x","y","sd")
      plot1 <- ggplot(data =si.new, aes(x,y))+ ggtitle("Intensity vs Concentration")+
        geom_point(colour = "black", na.rm = TRUE)+
        geom_smooth(method = "lm", formula = y~x, se = FALSE, colour = "black")+
        geom_errorbar(aes(ymin= y-sd, ymax=y+sd), width=.2,
                      position=position_dodge(0.05))+
        xlab("Concentration (nM)") +
        ylab("Standardized Intensity (tl/cl) [arbitrary unit]")+
        stat_poly_eq(formula = y~x, aes(label = paste(..eq.label.., ..rr.label..,
                                                      sep = "~~~")),
                     parse = TRUE)
      plot1

````
95% Confidence Interval:

------------------------------------------------------------------------------------

````{r, echo=FALSE, results='asis'}

x <- conf_new()

knitr::kable(x,format = "markdown")

````



95% Confidence Interval:

------------------------------------------------------------------------------------

````{r, echo=FALSE, results='asis'}

x <- conf_new()

knitr::kable(x, format = "markdown")

````


Correlation:

------------------------------------------------------------------------------------

````{r, echo=FALSE, results='asis'}

x <- cor_new()

knitr::kable(x, format = "markdown")

````

LOD_First Method:

------------------------------------------------------------------------------------

````{r, echo=FALSE, results='asis'}

x <- lod_new()

knitr::kable(x, format = "markdown")

````

LOD_Second Method:

------------------------------------------------------------------------------------

````{r, echo=FALSE, results='asis'}

x <- lod_new2()

knitr::kable(x, format = "markdown")

````

Calculated Concentration:

------------------------------------------------------------------------------------

````{r, echo=FALSE, results='asis'}

x <- concentration()

knitr::kable(x, format = "markdown")

````


Settings used during implementation:

--------------------------------------------

````{r, echo=FALSE, results='asis'}

cat("Select the type of file: ", input$filetype, "\n\n")

cat("Intensity value: ", input$yin, "\n\n")

cat("Slope value: ", input$mslp, "\n\n")

cat("Intercept value: ", input$cint, "\n\n")

````



Session Information:

--------------------------------------------

````{r, echo=FALSE, results='asis'}

sessionInfo("GNSplex")

````
